// Flat config for the whole workspace. Per-app rules go in the app's own
// eslint.config.mjs, which extends this one.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      // Generated by Next.js on every build; not ours to lint.
      "**/next-env.d.ts",
      "**/.next/**",
      "**/dist/**",
      "**/drizzle/meta/**",
      "**/playwright-report/**",
      "**/test-results/**",
      ".diagrams/**",
      "docs/architecture/diagrams/**",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    rules: {
      // An unused argument is often a signature being honoured, not a mistake.
      // An unused local almost never is.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // Services return Result<T> (see the backend's lib/result). A thrown error
      // that escapes a service is a bug in the service, not a control flow.
      "@typescript-eslint/no-explicit-any": "error",
      "no-console": ["warn", { allow: ["warn", "error"] }],
      eqeqeq: ["error", "smart"],
    },
  },

  // Operator tools and process entrypoints are supposed to talk: a server that
  // starts silently and a migration that reports nothing are both worse than a
  // line of output.
  {
    files: [
      "scripts/**/*.ts",
      "**/*.config.*",
      "**/server.ts",
      "**/seed.ts",
      "**/migrate.ts",
      "**/drizzle.config.ts",
    ],
    rules: { "no-console": "off" },
  },

  prettier,
);
